### ISSUE TITLE
[Fix]posix_memalign符合分配语义

### ISSUE THREAD

**Issue by NaturalSelect** [NaturalSelect/stdx#26]
https://github.com/NaturalSelect/stdx/blob/becd9eaba30885b45ac86513215e345274e49276/src/stdx/buffer.cpp#L136

**Comment by NaturalSelect** [comment]
void stdx::_Buffer::memalign(size_t align)
{
	char* buf = nullptr;
	stdx::posix_memalign((void**)&buf, align, m_size);
	std::swap(buf,m_data);
       stdx::free(buf);
}

**Comment by NaturalSelect** [comment]
void stdx::_Buffer::memalign(size_t align)
{
    char* buf = nullptr;
    stdx::posix_memalign((void**)&buf, align, m_size);
    {
        char *tmp = m_data;
        m_data = buf;
        buf = tmp;
    }
    stdx::free(buf);
}

**Comment by NaturalSelect** [comment]
void stdx::_Buffer::memalign(size_t align)
{
    char* buf = nullptr;
    stdx::posix_memalign((void**)&buf, align, m_size);
    {
        char *tmp = m_data;
        m_data = buf;
        buf = tmp;
    }
    stdx::free(buf);
}

**Comment by czm23333** [comment]
Duplicate of #793b75c
